apiVersion: dapr.io/v1alpha1
kind: Subscription
metadata:
  name: notifications-subscritpion
spec:
  topic: "{{ .Release.Name }}-notifications"
  route: /notifications
  pubsubname: notifications-pubsub
scopes: 
- subscriber-app