apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: write-app
spec:
  template:
    metadata:
      annotations:  
        dapr.io/app-id: write-app
        dapr.io/app-port: "8080"
        dapr.io/enabled: "true" 
        dapr.io/metrics-port: "9092"
        autoscaling.knative.dev/min-scale: "{{ .Values.minScale }}"
{{ if .Values.inVcluster }}   
        dapr.io/disable-builtin-k8s-secret-store: "true"     
{{- end}}
    spec:
      containerConcurrency: 0
      containers:
        - image: docker.io/salaboy/write-values-bbf0e73c38257c6528fd36ab9b562bf8@sha256:393338dec76d81a88ec028340051815d64d5cc59f9ee3fc7b0111c642ce745e9
          name: user-container
          env: 
          - name: STATESTORE_NAME
            value: statestore
          - name: TENANT_ID
            value: {{ .Release.Name }}  
          - name: PUB_SUB_TOPIC
            value: "{{ .Release.Name }}-notifications"  
          livenessProbe:
            httpGet:
              path: /health/readiness
              port: 8080
          readinessProbe:
            httpGet:
              path: /health/liveness
              port: 8080