apiVersion: dapr.io/v1alpha1
kind: Subscription
metadata:
  name: notifications-subscritpion
spec:
  topic: tenant-a-notifications 
  route: /notifications
  pubsubname: notifications-pubsub
scopes: 
- subscriber-app